--[[--------------------------------------------------------------------------
proto/items.lua -- item metadata loader (table produced by tools/extract_appearances.py)

Two consumers:
  * proto/parser.lua cannot decode the map without FLAGS1: every item on the wire is
    followed by a variable number of attribute bytes, and which blocks are present is
    decided purely by per-item-id asset flags (docs/appearances-assets.md sec.3.1).
  * the bot layer needs the walkability / interaction flags and the per-item scalars
    (docs/vbot/gaps.md P0-1, docs/vbot/pathfinding.md sec.4).

Generated by:  python tools/extract_appearances.py
Regenerate whenever data/things/1530/appearances-*.dat changes (see assets/README.md).

============================================================================
 FILE FORMAT -- assets/items1530.bin   (all integers little-endian, unsigned)
 This block is duplicated verbatim at the top of tools/extract_appearances.py.
============================================================================
 off  size  field              value for this asset set
   0     4  magic              "LCIT"
   4     1  version            2                      (v1 = 1; the loader accepts both)
   5     1  headerSize         40                     (v1 = 32)
   6     2  categoryCount      4      (item, creature/outfit, effect, missile)
   8     4  itemArrayLen       62145  (maxItemId+1; valid ids 1..62144)
  12     4  creatureArrayLen   10004
  16     4  effectArrayLen       344
  20     4  missileArrayLen       83
  24     4  objectCount        43536
  28     2  contentRevision    42196   (diagnostic only: the login packet must re-parse
                                        assets.json.sha256 at runtime)
  30     2  reserved           0
  32     1  sectionCount       12
  33     3  reserved           0,0,0
  36     4  sectionTableOff    40
  40  12*N  section directory
 ...        section payloads (in directory order, each 4-byte aligned)

 The first 32 bytes are byte-identical in layout to v1, so a v1 header parser reads
 itemArrayLen/objectCount/contentRevision out of a v2 file unchanged.  Everything new
 hangs off the section directory, so v3 may add sections without breaking this loader:
 an unknown sectionId is skipped, and a MISSING section reads as all-zero.

 SECTION DIRECTORY ENTRY (12 bytes)
   0  1  sectionId
   1  1  elemSize        bytes per item id (0 for blob/index sections)
   2  2  reserved        0
   4  4  offset          absolute byte offset in the file
   8  4  byteLength

 SECTIONS
   id  name          elemSize  length                 content
    1  FLAGS1           1      itemArrayLen  62145    v1 bits, UNCHANGED (parser depends on them)
    2  FLAGS2           1      itemArrayLen  62145    movement / stack-priority bits
    3  FLAGS3           1      itemArrayLen  62145    interaction bits
    4  FLAGS4           1      itemArrayLen  62145    misc bits
    5  GROUNDSPEED      2      2*itemArrayLen 124290  bank.waypoints (0 = not a ground; max 1200)
    6  MINIMAPCOLOR     1      itemArrayLen  62145    automap.color (0 = none; max 215)
    7  ELEVATION        1      itemArrayLen  62145    height.elevation (0..24 observed)
    8  LENSHELP         2      2*itemArrayLen 124290  lenshelp.id (0 = none; 1104/1105 matter)
    9  CLOTHSLOT        1      itemArrayLen  62145    clothes.slot (0 = none; max 12)
   10  NAMEIDX          6      6*8951 = 53706         sparse, ASCENDING by id:
                                                        u16 itemId, u32 offsetIntoNameBlob
   11  NAMEBLOB         1      149730                 concatenated NUL-terminated UTF-8
   12  FLAGS5           1      itemArrayLen  62145    bits that v1's FLAGS1 conflates

 FLAGS1 (unchanged from v1 -- do not renumber; proto/parser.lua reads these)
   0x01 CUMULATIVE   cumulative(6) | liquidcontainer(19) | liquidpool(12)
   0x02 WEAROUT      wearout(53)
   0x04 EXPIRE       clockexpire(54) | expire(55) | expirestop(56)
   0x08 CONTAINER    container(5)
   0x10 CLASSIFY     upgradeclassification(48).upgrade_classification > 0
   0x20 PODIUM       show_off_socket(46)
   0x40 DECOKIT      deco_kit(57)
   0x80 (spare)

 FLAGS2 -- movement / stack priority   (proto field #, thingtype.cpp line)
   0x01 GROUND            has_bank()               #1   PRESENCE ONLY   :179
   0x02 GROUND_BORDER     clip                     #2   has && value    :184
   0x04 ON_BOTTOM         has_bottom()             #3   PRESENCE ONLY   :188
   0x08 ON_TOP            has_top()                #4   PRESENCE ONLY   :192
   0x10 NOT_WALKABLE      unpass                   #13  has && value    :230
   0x20 NOT_PATHABLE      avoid                    #16  has && value    :242
   0x40 NOT_MOVEABLE      unmove                   #14  has && value    :234
   0x80 BLOCK_PROJECTILE  unsight                  #15  has && value    :238

 FLAGS3 -- interaction
   0x01 PICKUPABLE        take                     #18  :248
   0x02 USABLE            usable                   #7   :212
   0x04 MULTIUSE          multiuse                 #9   :204
   0x08 FORCE_USE         forceuse                 #8   :208
   0x10 FLUID_CONTAINER   liquidcontainer          #19  :252
   0x20 SPLASH            liquidpool               #12  :226
   0x40 HANGABLE          hang                     #20  :256
   0x80 WRITABLE          has_write() | has_write_once()  #10/#11 PRESENCE  :216/:221

 FLAGS4 -- misc
   0x01 ROTATEABLE        rotate                   #22  :285
   0x02 FULL_GROUND       fullbank                 #32  :325
   0x04 IGNORE_LOOK       ignore_look              #33  :329
   0x08 CORPSE            corpse                   #42  (no C++ flag; loot heuristic)
   0x10 PLAYER_CORPSE     player_corpse            #43
   0x20 LYING_OBJECT      lying_object             #28  :307
   0x40 WRAPABLE          wrap                     #37  :362
   0x80 UNWRAPABLE        unwrap                   #38  :366

 FLAGS5 -- bits FLAGS1 cannot express without changing v1 semantics
   0x01 STACKABLE         cumulative(6) ALONE      -- C++ ThingFlagAttrStackable, :200.
                          FLAGS1's CUMULATIVE also covers liquidcontainer/liquidpool
                          (they take the same u8 on the wire), which is a PROTOCOL-READ
                          bit, not Item::isStackable.  targetbot/looting.lua:285 merges
                          stacks on isStackable(), so the two must not be conflated.
   0x02 MARKET            has_market()             #36  PRESENCE  :340
                          ThingType only copies m_name into m_market.name inside this
                          branch, so `Item.create(id):getMarketData().name` -- what every
                          vBot name lookup actually calls -- is EMPTY for a named item
                          with no market block (3 852 of the 8 951 named ids, gold coin
                          among them).  items.name() returns the raw name, and
                          items.marketName() reproduces the vBot-visible value.
   0x04 ELEVATION         has_height()             #27  PRESENCE  :302
                          ThingType::hasElevation() is the FLAG, not `m_elevation > 0`:
                          4 ids carry height{elevation=0} and still increment
                          Tile::m_elevation (tile.cpp:1011-1012), which hasElevation(3)
                          reads.  The ELEVATION column alone cannot express them.
   0x08..0x80 (spare)

 NOTE 1: `bank`, `bottom`, `top`, `write`, `write_once`, `height`, `automap`, `lenshelp`,
         `clothes` and `market` are PRESENCE tests in C++ (has_x() with no value test) --
         do not require value != 0.  Every other boolean is has_x() && x().
         Measured on this asset set: NO varint boolean among the extracted fields is ever
         encoded with value 0, so presence and truth agree everywhere here.  The
         distinction is implemented anyway, because a future asset set may differ.
 NOTE 2: there is NO floor-change bit at 1530.  ThingFlagAttrFloorChange (const.h:1298) is
         only ever set from the legacy .dat path (thingtype.cpp:1096), so
         Tile::hasFloorChange() is permanently false.  Floor changes are inferred from
         LENSHELP (only 1104 and 1105 -- ladders 1100 and rope spots 1102 are deliberately
         NOT floor changes) + GROUND + NOT_PATHABLE + MINIMAPCOLOR 210..213, exactly as
         cavebot/walking.lua:102,117-160 does.
 NOTE 3: bank present but waypoints absent -> groundSpeed 0.  Tile::getGroundSpeed() returns
         that 0 VERBATIM; the 100 fallback applies only when the tile has no ground item at
         all (tile.cpp:562-569).  Creature::getStepDuration() separately substitutes 150 for
         a zero result (creature.cpp:1120-1121).  Keep BOTH fallbacks at their own call
         sites and do not "fix" a zero ground speed here.
============================================================================

 Id semantics (mirrors ThingTypeManager::isValidDatId + the dense resize(maxId+1)):
   * id 0            -> ERROR (never a valid item id)
   * id > MAX_ID     -> ERROR (Item::setId clamps to 0 and getItem throws)
   * 1 <= id <= MAX_ID with no appearance ("hole") -> 0 / nil, NOT an error
 Every numeric accessor obeys this; items.name/marketName return nil instead of 0.
--------------------------------------------------------------------------]]

local bit = require('bit')
local band = bit.band

local items = {}

-- FLAGS1 bits (v1; API.md) -----------------------------------------------------
items.CUMULATIVE = 0x01   -- count/subtype u8
items.WEAROUT    = 0x02
items.EXPIRE     = 0x04
items.CONTAINER  = 0x08
items.CLASSIFY   = 0x10   -- upgradeclassification > 0 -> tier u8
items.PODIUM     = 0x20
items.DECOKIT    = 0x40

-- FLAGS2 bits ------------------------------------------------------------------
items.GROUND            = 0x01
items.GROUND_BORDER     = 0x02
items.ON_BOTTOM         = 0x04
items.ON_TOP            = 0x08
items.NOT_WALKABLE      = 0x10
items.NOT_PATHABLE      = 0x20
items.NOT_MOVEABLE      = 0x40
items.BLOCK_PROJECTILE  = 0x80
-- the four "stack priority" bits together (Thing::isCommon is their complement)
items.STACK_CLASS_MASK  = 0x0F

-- FLAGS3 bits ------------------------------------------------------------------
items.PICKUPABLE      = 0x01
items.USABLE          = 0x02
items.MULTIUSE        = 0x04
items.FORCE_USE       = 0x08
items.FLUID_CONTAINER = 0x10
items.SPLASH          = 0x20
items.HANGABLE        = 0x40
items.WRITABLE        = 0x80

-- FLAGS4 bits ------------------------------------------------------------------
items.ROTATEABLE    = 0x01
items.FULL_GROUND   = 0x02
items.IGNORE_LOOK   = 0x04
items.CORPSE        = 0x08
items.PLAYER_CORPSE = 0x10
items.LYING_OBJECT  = 0x20
items.WRAPABLE      = 0x40
items.UNWRAPABLE    = 0x80

-- FLAGS5 bits ------------------------------------------------------------------
items.STACKABLE     = 0x01
items.MARKET        = 0x02
items.ELEVATION_BIT = 0x04

-- section ids ------------------------------------------------------------------
items.S_FLAGS1       = 1
items.S_FLAGS2       = 2
items.S_FLAGS3       = 3
items.S_FLAGS4       = 4
items.S_GROUNDSPEED  = 5
items.S_MINIMAPCOLOR = 6
items.S_ELEVATION    = 7
items.S_LENSHELP     = 8
items.S_CLOTHSLOT    = 9
items.S_NAMEIDX      = 10
items.S_NAMEBLOB     = 11
items.S_FLAGS5       = 12

items.MAGIC          = 'LCIT'
items.VERSION        = 2      -- the version this module writes/expects
items.HEADER_SIZE    = 40     -- v2
items.HEADER_SIZE_V1 = 32
items.DIR_ENTRY_SIZE = 12

-- Thing::getStackPriority (thing.cpp:54-77).  Creatures are 4 and are the caller's job.
items.PRIO_GROUND        = 0
items.PRIO_GROUND_BORDER = 1
items.PRIO_ON_BOTTOM     = 2
items.PRIO_ON_TOP        = 3
items.PRIO_CREATURE      = 4
items.PRIO_COMMON        = 5

-- populated by load()
items.MAX_ID = 0              -- max valid item id (itemArrayLen - 1)
items.COUNT  = 0              -- number of item appearances actually present
items.CREATURE_MAX_ID = 0
items.EFFECT_MAX_ID   = 0
items.MISSILE_MAX_ID  = 0
items.CONTENT_REVISION = 0    -- diagnostic only; re-parse assets.json.sha256 for the wire
items.fileVersion = 0         -- 1 or 2: what was actually on disk
items.path = nil
items.loaded = false
items.sections = nil          -- [sectionId] = {elem=, off=, len=}  (off is 0-based)

local BLOB = nil              -- the whole file as a Lua string
local SEC  = nil              -- alias of items.sections
local OFF1, OFF2, OFF3, OFF4, OFF5 = nil, nil, nil, nil, nil  -- hot flag-section offsets
local NAMEIDX_OFF, NAMEIDX_N, NAMEBLOB_OFF = 0, 0, 0
local NAMECACHE = nil

local function u16le(s, o)
  local a, b = s:byte(o, o + 1)
  return a + b * 256
end

local function u32le(s, o)
  local a, b, c, d = s:byte(o, o + 3)
  return a + b * 256 + c * 65536 + d * 16777216
end

-- Resolve a default location: <dir of this file>/../assets/items1530.bin, then cwd.
local function defaultPaths()
  local out = {}
  local src = debug.getinfo(1, 'S').source
  if src:sub(1, 1) == '@' then
    local dir = src:sub(2):match('^(.*)[/\\][^/\\]*$')
    if dir then
      out[#out + 1] = dir .. '/../assets/items1530.bin'
    end
  end
  out[#out + 1] = 'assets/items1530.bin'
  out[#out + 1] = 'items1530.bin'
  return out
end

-- ---------------------------------------------------------------------------
-- load
-- ---------------------------------------------------------------------------
-- path may be a file, or a directory containing items1530.bin, or nil (defaults).
function items.load(path)
  local candidates
  if path == nil then
    candidates = defaultPaths()
  elseif path:match('items1530%.bin$') then
    candidates = { path }
  else
    candidates = { path .. '/items1530.bin', path }
  end

  local f, used
  for _, p in ipairs(candidates) do
    local h = io.open(p, 'rb')
    if h then f, used = h, p break end
  end
  if not f then
    error('items.load: cannot open item table (tried: ' .. table.concat(candidates, ', ') .. ')', 2)
  end
  local blob = f:read('*a')
  f:close()
  if not blob then
    error('items.load: ' .. used .. ' could not be read', 2)
  end

  local function fail(fmt, ...)
    error('items.load: ' .. used .. ' ' .. string.format(fmt, ...), 3)
  end

  if #blob < items.HEADER_SIZE_V1 then fail('is truncated (header)') end
  if blob:sub(1, 4) ~= items.MAGIC then
    fail('bad magic %q (expected %q)', blob:sub(1, 4), items.MAGIC)
  end
  local version    = blob:byte(5)
  local headerSize = blob:byte(6)
  if version ~= 1 and version ~= 2 then
    fail('unsupported version %d (this loader reads 1 and 2)', version)
  end
  local wantHeader = (version == 1) and items.HEADER_SIZE_V1 or items.HEADER_SIZE
  if headerSize ~= wantHeader then
    fail('bad headerSize %d (expected %d for version %d)', headerSize, wantHeader, version)
  end
  if #blob < headerSize then fail('is truncated (header)') end

  local categoryCount = u16le(blob, 7)
  if categoryCount ~= 4 then
    fail('bad categoryCount %d (expected 4)', categoryCount)
  end

  local itemLen     = u32le(blob, 9)
  local creatureLen = u32le(blob, 13)
  local effectLen   = u32le(blob, 17)
  local missileLen  = u32le(blob, 21)
  local objectCount = u32le(blob, 25)
  local revision    = u16le(blob, 29)

  if itemLen < 2 or itemLen > 0x10000 then
    fail('implausible itemArrayLen %d', itemLen)
  end

  local sections = {}
  if version == 1 then
    -- v1: a single implicit FLAGS1 payload right after the 32-byte header.
    if #blob < 32 + itemLen then
      fail('truncated table (got %d bytes, want %d)', #blob - 32, itemLen)
    end
    if #blob > 32 + itemLen then
      fail('has trailing garbage after the table')
    end
    sections[items.S_FLAGS1] = { elem = 1, off = 32, len = itemLen }
  else
    local sectionCount = blob:byte(33)
    local dirOff       = u32le(blob, 37)
    if sectionCount < 1 or sectionCount > 64 then
      fail('implausible sectionCount %d', sectionCount)
    end
    if dirOff + sectionCount * items.DIR_ENTRY_SIZE > #blob then
      fail('section directory overruns the file')
    end
    for i = 0, sectionCount - 1 do
      local o   = dirOff + i * items.DIR_ENTRY_SIZE     -- 0-based
      local sid = blob:byte(o + 1)
      local elem = blob:byte(o + 2)
      local soff = u32le(blob, o + 5)
      local slen = u32le(blob, o + 9)
      if soff + slen > #blob then
        fail('section %d (offset %d, length %d) overruns the file', sid, soff, slen)
      end
      if sections[sid] then fail('duplicate section id %d in the directory', sid) end
      sections[sid] = { elem = elem, off = soff, len = slen }
    end
    -- FLAGS1 is the one section the protocol parser cannot live without.
    local s1 = sections[items.S_FLAGS1]
    if not s1 then fail('has no FLAGS1 section') end
    if s1.len ~= itemLen then
      fail('FLAGS1 length %d does not match itemArrayLen %d', s1.len, itemLen)
    end
  end

  -- Dense sections must be exactly elem*itemArrayLen so an in-range id can never
  -- read past the section; that check is what lets the accessors skip a length test.
  local DENSE = { [items.S_FLAGS1] = 1, [items.S_FLAGS2] = 1, [items.S_FLAGS3] = 1,
                  [items.S_FLAGS4] = 1, [items.S_FLAGS5] = 1, [items.S_MINIMAPCOLOR] = 1,
                  [items.S_ELEVATION] = 1, [items.S_CLOTHSLOT] = 1,
                  [items.S_GROUNDSPEED] = 2, [items.S_LENSHELP] = 2 }
  for sid, want in pairs(DENSE) do
    local s = sections[sid]
    if s then
      if s.elem ~= want then fail('section %d has elemSize %d (expected %d)', sid, s.elem, want) end
      if s.len ~= want * itemLen then
        fail('section %d has length %d (expected %d)', sid, s.len, want * itemLen)
      end
    end
  end
  if blob:byte(sections[items.S_FLAGS1].off + 1) ~= 0 then
    fail('FLAGS1 slot 0 must be 0x00, got 0x%02X', blob:byte(sections[items.S_FLAGS1].off + 1))
  end

  local nameIdx, nameBlob = sections[items.S_NAMEIDX], sections[items.S_NAMEBLOB]
  if nameIdx and not nameBlob then fail('has NAMEIDX but no NAMEBLOB') end
  if nameIdx then
    if nameIdx.elem ~= 6 then fail('NAMEIDX elemSize %d (expected 6)', nameIdx.elem) end
    if nameIdx.len % 6 ~= 0 then fail('NAMEIDX length %d is not a multiple of 6', nameIdx.len) end
  end

  BLOB = blob
  SEC  = sections
  items.sections = sections
  OFF1 = sections[items.S_FLAGS1].off
  OFF2 = sections[items.S_FLAGS2] and sections[items.S_FLAGS2].off
  OFF3 = sections[items.S_FLAGS3] and sections[items.S_FLAGS3].off
  OFF4 = sections[items.S_FLAGS4] and sections[items.S_FLAGS4].off
  OFF5 = sections[items.S_FLAGS5] and sections[items.S_FLAGS5].off
  if nameIdx then
    NAMEIDX_OFF, NAMEIDX_N, NAMEBLOB_OFF = nameIdx.off, nameIdx.len / 6, nameBlob.off
  else
    NAMEIDX_OFF, NAMEIDX_N, NAMEBLOB_OFF = 0, 0, 0
  end
  NAMECACHE = {}

  items.MAX_ID = itemLen - 1
  items.COUNT = objectCount
  items.CREATURE_MAX_ID = creatureLen - 1
  items.EFFECT_MAX_ID = effectLen - 1
  items.MISSILE_MAX_ID = missileLen - 1
  items.CONTENT_REVISION = revision
  items.fileVersion = version
  items.path = used
  items.loaded = true
  items.byteSize = #blob
  return items
end

function items.unload()
  BLOB, SEC, NAMECACHE = nil, nil, nil
  OFF1, OFF2, OFF3, OFF4, OFF5 = nil, nil, nil, nil, nil
  NAMEIDX_OFF, NAMEIDX_N, NAMEBLOB_OFF = 0, 0, 0
  items.sections = nil
  items.loaded = false
  items.path = nil
  items.fileVersion = 0
  items.byteSize = 0
  items.MAX_ID, items.COUNT = 0, 0
  items.CREATURE_MAX_ID, items.EFFECT_MAX_ID, items.MISSILE_MAX_ID = 0, 0, 0
  items.CONTENT_REVISION = 0
end

-- ---------------------------------------------------------------------------
-- column readers
-- ---------------------------------------------------------------------------
-- `who` is used only to build the error message, so the hot path never formats.
local function checkId(id, who)
  if BLOB == nil then
    error('items.' .. who .. ': item table not loaded (call items.load first)', 3)
  end
  if type(id) ~= 'number' or id ~= math.floor(id) then
    error('items.' .. who .. ': item id must be an integer, got ' .. tostring(id), 3)
  end
  if id < 1 or id > items.MAX_ID then
    error(string.format('items.%s: item id %d out of range 1..%d', who, id, items.MAX_ID), 3)
  end
end
items.checkId = checkId

-- Returns the FLAGS1 byte of an item id -- the v1 contract, unchanged.
-- 0 for holes and for ids in range with no flags; errors if id == 0 or id > MAX_ID.
function items.flags(id)
  checkId(id, 'flags')
  return BLOB:byte(OFF1 + id + 1)
end

function items.flags2(id)
  checkId(id, 'flags2')
  if not OFF2 then return 0 end
  return BLOB:byte(OFF2 + id + 1)
end

function items.flags3(id)
  checkId(id, 'flags3')
  if not OFF3 then return 0 end
  return BLOB:byte(OFF3 + id + 1)
end

function items.flags4(id)
  checkId(id, 'flags4')
  if not OFF4 then return 0 end
  return BLOB:byte(OFF4 + id + 1)
end

function items.flags5(id)
  checkId(id, 'flags5')
  if not OFF5 then return 0 end
  return BLOB:byte(OFF5 + id + 1)
end

local function col1(sid, id, who)
  checkId(id, who)
  local s = SEC[sid]
  if not s then return 0 end
  return BLOB:byte(s.off + id + 1)
end

local function col2(sid, id, who)
  checkId(id, who)
  local s = SEC[sid]
  if not s then return 0 end
  return u16le(BLOB, s.off + id * 2 + 1)
end

-- bank.waypoints.  0 means "no bank block, or a bank with no waypoints"; see NOTE 3 --
-- the 100 / 150 substitutions belong to Tile::getGroundSpeed and Creature::getStepDuration,
-- NOT here.
function items.groundSpeed(id)  return col2(items.S_GROUNDSPEED,  id, 'groundSpeed')  end
function items.minimapColor(id) return col1(items.S_MINIMAPCOLOR, id, 'minimapColor') end
function items.elevation(id)    return col1(items.S_ELEVATION,    id, 'elevation')    end
function items.lensHelp(id)     return col2(items.S_LENSHELP,     id, 'lensHelp')     end
function items.clothSlot(id)    return col1(items.S_CLOTHSLOT,    id, 'clothSlot')    end

-- Appearance.name, or nil.  The index is sparse and sorted, so this binary-searches and
-- memoises; loading does NOT materialise 8 951 Lua strings up front.
function items.name(id)
  checkId(id, 'name')
  if NAMEIDX_N == 0 then return nil end
  local hit = NAMECACHE[id]
  if hit ~= nil then
    if hit == false then return nil end
    return hit
  end
  local lo, hi = 0, NAMEIDX_N - 1
  while lo <= hi do
    local mid = math.floor((lo + hi) / 2)
    local o = NAMEIDX_OFF + mid * 6
    local key = u16le(BLOB, o + 1)
    if key == id then
      local off = u32le(BLOB, o + 3)
      local s = NAMEBLOB_OFF + off + 1
      local e = BLOB:find('\0', s, true)
      local name = BLOB:sub(s, (e or (s + 1)) - 1)
      NAMECACHE[id] = name
      return name
    elseif key < id then
      lo = mid + 1
    else
      hi = mid - 1
    end
  end
  NAMECACHE[id] = false
  return nil
end

-- What `Item.create(id):getMarketData().name` returns in the real client: ThingType only
-- copies m_name into m_market.name inside `if (flags.has_market())` (thingtype.cpp:340-357),
-- so a named item with no market block hands the bot an empty string.  vBot works around
-- that with hardcoded ids (analyzer.lua:401 for 3031 "gold coin").  nil, not '', so the
-- caller can tell "no market name" from "market name is empty".
function items.marketName(id)
  if band(items.flags5(id), items.MARKET) == 0 then return nil end
  return items.name(id)
end

-- ---------------------------------------------------------------------------
-- ThingTypeManager::isValidDatId equivalents (size checks, not existence checks)
-- ---------------------------------------------------------------------------
function items.isValidItemId(id)
  return type(id) == 'number' and id >= 1 and id <= items.MAX_ID
end

function items.isValidCreatureId(id)
  return type(id) == 'number' and id >= 1 and id <= items.CREATURE_MAX_ID
end

function items.isValidEffectId(id)
  return type(id) == 'number' and id >= 1 and id <= items.EFFECT_MAX_ID
end

function items.isValidMissileId(id)
  return type(id) == 'number' and id >= 1 and id <= items.MISSILE_MAX_ID
end

-- convenience predicate over FLAGS1 (no extra allocation)
function items.has(id, mask)
  return band(items.flags(id), mask) ~= 0
end

-- ---------------------------------------------------------------------------
-- derived predicates (docs/vbot/gaps.md P0-1, docs/vbot/pathfinding.md sec.4.2)
-- ---------------------------------------------------------------------------
function items.isGround(id)          return band(items.flags2(id), 0x01) ~= 0 end
function items.isGroundBorder(id)    return band(items.flags2(id), 0x02) ~= 0 end
function items.isOnBottom(id)        return band(items.flags2(id), 0x04) ~= 0 end
function items.isOnTop(id)           return band(items.flags2(id), 0x08) ~= 0 end
function items.isNotWalkable(id)     return band(items.flags2(id), 0x10) ~= 0 end
function items.isNotPathable(id)     return band(items.flags2(id), 0x20) ~= 0 end
function items.isNotMoveable(id)     return band(items.flags2(id), 0x40) ~= 0 end
function items.isBlockProjectile(id) return band(items.flags2(id), 0x80) ~= 0 end

function items.isPickupable(id)      return band(items.flags3(id), 0x01) ~= 0 end
function items.isUsable(id)          return band(items.flags3(id), 0x02) ~= 0 end
function items.isMultiUse(id)        return band(items.flags3(id), 0x04) ~= 0 end
function items.isForceUse(id)        return band(items.flags3(id), 0x08) ~= 0 end
function items.isFluidContainer(id)  return band(items.flags3(id), 0x10) ~= 0 end
function items.isSplash(id)          return band(items.flags3(id), 0x20) ~= 0 end
function items.isHangable(id)        return band(items.flags3(id), 0x40) ~= 0 end
function items.isWritable(id)        return band(items.flags3(id), 0x80) ~= 0 end

function items.isRotateable(id)      return band(items.flags4(id), 0x01) ~= 0 end
function items.isFullGround(id)      return band(items.flags4(id), 0x02) ~= 0 end
function items.isIgnoreLook(id)      return band(items.flags4(id), 0x04) ~= 0 end
function items.isCorpse(id)          return band(items.flags4(id), 0x08) ~= 0 end
function items.isPlayerCorpse(id)    return band(items.flags4(id), 0x10) ~= 0 end
function items.isLyingObject(id)     return band(items.flags4(id), 0x20) ~= 0 end
function items.isWrapable(id)        return band(items.flags4(id), 0x40) ~= 0 end
function items.isUnwrapable(id)      return band(items.flags4(id), 0x80) ~= 0 end

function items.isContainer(id)       return band(items.flags(id), items.CONTAINER) ~= 0 end
function items.hasMarket(id)         return band(items.flags5(id), items.MARKET) ~= 0 end

-- ThingType::hasElevation() -- the FLAG (has_height()), not `elevation(id) > 0`.
-- Tile::m_elevation counts things by this, and 4 ids carry height{elevation=0}.
function items.hasElevation(id)      return band(items.flags5(id), items.ELEVATION_BIT) ~= 0 end

-- Item::isStackable == ThingFlagAttrStackable == `cumulative` ALONE.  NOT FLAGS1's
-- CUMULATIVE bit, which the protocol reader also sets for liquidcontainer/liquidpool
-- (60 ids on this asset set).  targetbot/looting.lua:285 decides stack merging on this.
function items.isStackable(id)       return band(items.flags5(id), items.STACKABLE) ~= 0 end

-- Thing::isCommon (thing.h:67): not ground, not groundBorder, not onBottom, not onTop
-- (and not a creature -- creatures never reach this function).
function items.isCommon(id)
  return band(items.flags2(id), items.STACK_CLASS_MASK) == 0
end

-- Thing::getStackPriority (thing.cpp:54-77) for an ITEM.  Creatures are PRIO_CREATURE(4)
-- and are the caller's job; the `<= 800 && isSplash -> GROUND` clause is dead at 1530.
function items.stackPriority(id)
  local f = band(items.flags2(id), items.STACK_CLASS_MASK)
  if f == 0 then return items.PRIO_COMMON end
  if band(f, 0x01) ~= 0 then return items.PRIO_GROUND end
  if band(f, 0x02) ~= 0 then return items.PRIO_GROUND_BORDER end
  if band(f, 0x04) ~= 0 then return items.PRIO_ON_BOTTOM end
  return items.PRIO_ON_TOP
end

return items
