--[[--------------------------------------------------------------------------
proto/items.lua -- item metadata loader (flag table produced by tools/extract_appearances.py)

The parser cannot decode the map without this: every item on the wire is followed by a
variable number of attribute bytes, and which blocks are present is decided purely by
per-item-id asset flags (docs/appearances-assets.md sec.3.1).

Generated by:  python tools/extract_appearances.py
Regenerate whenever data/things/1530/appearances-*.dat changes (see assets/README.md).

============================================================================
 FILE FORMAT -- assets/items1530.bin   (all integers little-endian, unsigned)
 This block is duplicated verbatim at the top of tools/extract_appearances.py.
============================================================================
 off  size  field             value / meaning
   0     4  magic             ASCII "LCIT"
   4     1  version           1
   5     1  headerSize        32  (offset of the first flag byte)
   6     2  categoryCount     4   (item, creature/outfit, effect, missile)
   8     4  itemArrayLen      maxItemId + 1        (62145) -- valid item ids: 1 .. itemArrayLen-1
  12     4  creatureArrayLen  maxOutfitId + 1      (10004)
  16     4  effectArrayLen    maxEffectId + 1        (344)
  20     4  missileArrayLen   maxMissileId + 1        (83)
  24     4  objectCount       number of item appearances actually present (43536)
  28     2  contentRevision   diagnostic copy of assets.json.sha256 (42196).
                              NOT authoritative: the login packet must re-parse
                              assets.json.sha256 at runtime (docs sec.6 / VERIFIER).
  30     2  reserved          0
  32     N  flags[]           itemArrayLen bytes, flags[i] = flag byte of item id i.
                              index 0 (id 0) is always 0x00.
 total size = 32 + itemArrayLen bytes (= 62177 for this asset set)

 FLAG BYTE BITS (must match tools/extract_appearances.py and API.md exactly)
  bit 0  0x01  CUMULATIVE  read u8 count/subtype  <- cumulative(6) | liquidcontainer(19) | liquidpool(12)
  bit 1  0x02  WEAROUT     read u32 charges + u8  <- wearout(53)
  bit 2  0x04  EXPIRE      read u32 duration + u8 <- clockexpire(54) | expire(55) | expirestop(56)
  bit 3  0x08  CONTAINER   read u8 type + switch  <- container(5)
  bit 4  0x10  CLASSIFY    read u8 tier           <- upgradeclassification(48).upgrade_classification > 0
  bit 5  0x20  PODIUM      read podium block      <- show_off_socket(46)
  bit 6  0x40  DECOKIT     read u16               <- deco_kit(57)
  bit 7  0x80  (spare, always 0)
============================================================================

 Id semantics (mirrors ThingTypeManager::isValidDatId + the dense resize(maxId+1)):
   * id 0            -> ERROR (never a valid item id)
   * id > MAX_ID     -> ERROR (Item::setId clamps to 0 and getItem throws)
   * 1 <= id <= MAX_ID with no appearance ("hole") -> 0, NOT an error
--------------------------------------------------------------------------]]

local bit = require('bit')

local items = {}

-- flag bits (API.md)
items.CUMULATIVE = 0x01   -- count/subtype u8
items.WEAROUT    = 0x02
items.EXPIRE     = 0x04
items.CONTAINER  = 0x08
items.CLASSIFY   = 0x10   -- upgradeclassification > 0 -> tier u8
items.PODIUM     = 0x20
items.DECOKIT    = 0x40

items.MAGIC   = 'LCIT'
items.VERSION = 1
items.HEADER_SIZE = 32

-- populated by load()
items.MAX_ID = 0              -- max valid item id (itemArrayLen - 1)
items.COUNT  = 0              -- number of item appearances actually present
items.CREATURE_MAX_ID = 0
items.EFFECT_MAX_ID   = 0
items.MISSILE_MAX_ID  = 0
items.CONTENT_REVISION = 0    -- diagnostic only; re-parse assets.json.sha256 for the wire
items.path = nil
items.loaded = false

local FLAGS = nil             -- the raw flag string; FLAGS:byte(id+1) is the flag byte

local function u16le(s, o)
  local a, b = s:byte(o, o + 1)
  return a + b * 256
end

local function u32le(s, o)
  local a, b, c, d = s:byte(o, o + 3)
  return a + b * 256 + c * 65536 + d * 16777216
end

-- Resolve a default location: <dir of this file>/../assets/items1530.bin, then cwd.
local function defaultPaths()
  local out = {}
  local src = debug.getinfo(1, 'S').source
  if src:sub(1, 1) == '@' then
    local dir = src:sub(2):match('^(.*)[/\\][^/\\]*$')
    if dir then
      out[#out + 1] = dir .. '/../assets/items1530.bin'
    end
  end
  out[#out + 1] = 'assets/items1530.bin'
  out[#out + 1] = 'items1530.bin'
  return out
end

-- path may be a file, or a directory containing items1530.bin, or nil (defaults).
function items.load(path)
  local candidates
  if path == nil then
    candidates = defaultPaths()
  elseif path:match('items1530%.bin$') then
    candidates = { path }
  else
    candidates = { path .. '/items1530.bin', path }
  end

  local f, used
  for _, p in ipairs(candidates) do
    local h = io.open(p, 'rb')
    if h then f, used = h, p break end
  end
  if not f then
    error('items.load: cannot open item table (tried: ' .. table.concat(candidates, ', ') .. ')', 2)
  end

  local hdr = f:read(items.HEADER_SIZE)
  if not hdr or #hdr < items.HEADER_SIZE then
    f:close()
    error('items.load: ' .. used .. ' is truncated (header)', 2)
  end
  if hdr:sub(1, 4) ~= items.MAGIC then
    f:close()
    error(string.format('items.load: %s bad magic %q (expected %q)', used, hdr:sub(1, 4), items.MAGIC), 2)
  end
  local version    = hdr:byte(5)
  local headerSize = hdr:byte(6)
  if version ~= items.VERSION then
    f:close()
    error(string.format('items.load: %s unsupported version %d (expected %d)', used, version, items.VERSION), 2)
  end
  if headerSize ~= items.HEADER_SIZE then
    f:close()
    error(string.format('items.load: %s bad headerSize %d (expected %d)', used, headerSize, items.HEADER_SIZE), 2)
  end
  local categoryCount = u16le(hdr, 7)
  if categoryCount ~= 4 then
    f:close()
    error(string.format('items.load: %s bad categoryCount %d (expected 4)', used, categoryCount), 2)
  end

  local itemLen     = u32le(hdr, 9)
  local creatureLen = u32le(hdr, 13)
  local effectLen   = u32le(hdr, 17)
  local missileLen  = u32le(hdr, 21)
  local objectCount = u32le(hdr, 25)
  local revision    = u16le(hdr, 29)

  if itemLen < 2 or itemLen > 0x10000 then
    f:close()
    error(string.format('items.load: %s implausible itemArrayLen %d', used, itemLen), 2)
  end

  local body = f:read(itemLen)
  local extra = f:read(1)
  f:close()
  if not body or #body ~= itemLen then
    error(string.format('items.load: %s truncated table (got %d bytes, want %d)',
      used, body and #body or 0, itemLen), 2)
  end
  if extra ~= nil and #extra > 0 then
    error(string.format('items.load: %s has trailing garbage after the table', used), 2)
  end
  if body:byte(1) ~= 0 then
    error(string.format('items.load: %s slot 0 must be 0x00, got 0x%02X', used, body:byte(1)), 2)
  end

  FLAGS = body
  items.MAX_ID = itemLen - 1
  items.COUNT = objectCount
  items.CREATURE_MAX_ID = creatureLen - 1
  items.EFFECT_MAX_ID = effectLen - 1
  items.MISSILE_MAX_ID = missileLen - 1
  items.CONTENT_REVISION = revision
  items.path = used
  items.loaded = true
  return items
end

-- Returns the flag byte of an item id.
-- 0 for holes and for ids in range with no flags; errors if id == 0 or id > MAX_ID.
function items.flags(id)
  if FLAGS == nil then
    error('items.flags: item table not loaded (call items.load first)', 2)
  end
  if type(id) ~= 'number' or id ~= math.floor(id) then
    error('items.flags: item id must be an integer, got ' .. tostring(id), 2)
  end
  if id < 1 or id > items.MAX_ID then
    error(string.format('items.flags: item id %d out of range 1..%d', id, items.MAX_ID), 2)
  end
  return FLAGS:byte(id + 1)
end

-- ThingTypeManager::isValidDatId equivalents (size checks, not existence checks).
function items.isValidItemId(id)
  return type(id) == 'number' and id >= 1 and id <= items.MAX_ID
end

function items.isValidCreatureId(id)
  return type(id) == 'number' and id >= 1 and id <= items.CREATURE_MAX_ID
end

function items.isValidEffectId(id)
  return type(id) == 'number' and id >= 1 and id <= items.EFFECT_MAX_ID
end

function items.isValidMissileId(id)
  return type(id) == 'number' and id >= 1 and id <= items.MISSILE_MAX_ID
end

-- convenience predicates (no extra allocation)
function items.has(id, mask)
  return bit.band(items.flags(id), mask) ~= 0
end

function items.unload()
  FLAGS = nil
  items.loaded = false
  items.path = nil
  items.MAX_ID, items.COUNT = 0, 0
  items.CREATURE_MAX_ID, items.EFFECT_MAX_ID, items.MISSILE_MAX_ID = 0, 0, 0
  items.CONTENT_REVISION = 0
end

return items
