-- GENERATED by tools/extract_vbot_data.lua -- DO NOT EDIT BY HAND.
-- Source: modules/gamelib/spells.lua  SpellInfo['Default']
-- words(lowercase) -> { id, level, mana, exhaustion, group = {[groupId]=ms}, name }
return {
  ["adana ani"] = {
    ["exhaustion"] = 2000,
    ["group"] = {
      [3] = 2000,
    },
    ["id"] = 54,
    ["level"] = 54,
    ["mana"] = 1400,
    ["name"] = "Paralyze Rune",
  },
  ["adana mort"] = {
    ["exhaustion"] = 2000,
    ["group"] = {
      [3] = 2000,
    },
    ["id"] = 83,
    ["level"] = 27,
    ["mana"] = 600,
    ["name"] = "Animate Dead Rune",
  },
  ["adana pox"] = {
    ["exhaustion"] = 2000,
    ["group"] = {
      [3] = 2000,
    },
    ["id"] = 31,
    ["level"] = 15,
    ["mana"] = 200,
    ["name"] = "Cure Poison Rune",
  },
  ["adeta sio"] = {
    ["exhaustion"] = 2000,
    ["group"] = {
      [3] = 2000,
    },
    ["id"] = 12,
    ["level"] = 16,
    ["mana"] = 200,
    ["name"] = "Convince Creature Rune",
  },
  ["adevo grav flam"] = {
    ["exhaustion"] = 2000,
    ["group"] = {
      [3] = 2000,
    },
    ["id"] = 25,
    ["level"] = 15,
    ["mana"] = 240,
    ["name"] = "Fire Field Rune",
  },
  ["adevo grav pox"] = {
    ["exhaustion"] = 2000,
    ["group"] = {
      [3] = 2000,
    },
    ["id"] = 26,
    ["level"] = 14,
    ["mana"] = 200,
    ["name"] = "Poison Field Rune",
  },
  ["adevo grav tera"] = {
    ["exhaustion"] = 2000,
    ["group"] = {
      [3] = 2000,
    },
    ["id"] = 86,
    ["level"] = 32,
    ["mana"] = 750,
    ["name"] = "Magic Wall Rune",
  },
  ["adevo grav vis"] = {
    ["exhaustion"] = 2000,
    ["group"] = {
      [3] = 2000,
    },
    ["id"] = 27,
    ["level"] = 18,
    ["mana"] = 320,
    ["name"] = "Energy Field Rune",
  },
  ["adevo grav vita"] = {
    ["exhaustion"] = 2000,
    ["group"] = {
      [3] = 2000,
    },
    ["id"] = 94,
    ["level"] = 27,
    ["mana"] = 600,
    ["name"] = "Wild Growth Rune",
  },
  ["adevo ina"] = {
    ["exhaustion"] = 2000,
    ["group"] = {
      [3] = 2000,
    },
    ["id"] = 14,
    ["level"] = 27,
    ["mana"] = 600,
    ["name"] = "Chameleon Rune",
  },
  ["adevo mas flam"] = {
    ["exhaustion"] = 2000,
    ["group"] = {
      [3] = 2000,
    },
    ["id"] = 17,
    ["level"] = 27,
    ["mana"] = 600,
    ["name"] = "Fire Bomb Rune",
  },
  ["adevo mas grav flam"] = {
    ["exhaustion"] = 2000,
    ["group"] = {
      [3] = 2000,
    },
    ["id"] = 28,
    ["level"] = 33,
    ["mana"] = 780,
    ["name"] = "Fire Wall Rune",
  },
  ["adevo mas grav pox"] = {
    ["exhaustion"] = 2000,
    ["group"] = {
      [3] = 2000,
    },
    ["id"] = 32,
    ["level"] = 29,
    ["mana"] = 640,
    ["name"] = "Poison Wall Rune",
  },
  ["adevo mas grav vis"] = {
    ["exhaustion"] = 2000,
    ["group"] = {
      [3] = 2000,
    },
    ["id"] = 33,
    ["level"] = 41,
    ["mana"] = 1000,
    ["name"] = "Energy Wall Rune",
  },
  ["adevo mas hur"] = {
    ["exhaustion"] = 2000,
    ["group"] = {
      [3] = 2000,
    },
    ["id"] = 18,
    ["level"] = 31,
    ["mana"] = 570,
    ["name"] = "Explosion Rune",
  },
  ["adevo mas pox"] = {
    ["exhaustion"] = 2000,
    ["group"] = {
      [3] = 2000,
    },
    ["id"] = 91,
    ["level"] = 25,
    ["mana"] = 520,
    ["name"] = "Poison Bomb Rune",
  },
  ["adevo mas vis"] = {
    ["exhaustion"] = 2000,
    ["group"] = {
      [3] = 2000,
    },
    ["id"] = 55,
    ["level"] = 37,
    ["mana"] = 880,
    ["name"] = "Energy Bomb Rune",
  },
  ["adevo res flam"] = {
    ["exhaustion"] = 2000,
    ["group"] = {
      [3] = 2000,
    },
    ["id"] = 50,
    ["level"] = 27,
    ["mana"] = 420,
    ["name"] = "Soulfire Rune",
  },
  ["adito grav"] = {
    ["exhaustion"] = 2000,
    ["group"] = {
      [3] = 2000,
    },
    ["id"] = 30,
    ["level"] = 17,
    ["mana"] = 120,
    ["name"] = "Destroy Field Rune",
  },
  ["adito tera"] = {
    ["exhaustion"] = 2000,
    ["group"] = {
      [3] = 2000,
    },
    ["id"] = 78,
    ["level"] = 21,
    ["mana"] = 200,
    ["name"] = "Disintegrate Rune",
  },
  ["adori dis min vis"] = {
    ["exhaustion"] = 2000,
    ["group"] = {
      [3] = 2000,
    },
    ["id"] = 0,
    ["level"] = 1,
    ["mana"] = 5,
    ["name"] = "Lightest Magic Missile",
  },
  ["adori flam"] = {
    ["exhaustion"] = 2000,
    ["group"] = {
      [3] = 2000,
    },
    ["id"] = 15,
    ["level"] = 27,
    ["mana"] = 460,
    ["name"] = "Fireball Rune",
  },
  ["adori frigo"] = {
    ["exhaustion"] = 2000,
    ["group"] = {
      [3] = 2000,
    },
    ["id"] = 114,
    ["level"] = 28,
    ["mana"] = 460,
    ["name"] = "Icicle Rune",
  },
  ["adori gran mort"] = {
    ["exhaustion"] = 2000,
    ["group"] = {
      [3] = 2000,
    },
    ["id"] = 21,
    ["level"] = 45,
    ["mana"] = 985,
    ["name"] = "Sudden Death Rune",
  },
  ["adori mas flam"] = {
    ["exhaustion"] = 2000,
    ["group"] = {
      [3] = 2000,
    },
    ["id"] = 16,
    ["level"] = 30,
    ["mana"] = 530,
    ["name"] = "Great Fireball Rune",
  },
  ["adori mas frigo"] = {
    ["exhaustion"] = 2000,
    ["group"] = {
      [3] = 2000,
    },
    ["id"] = 115,
    ["level"] = 30,
    ["mana"] = 530,
    ["name"] = "Avalanche Rune",
  },
  ["adori mas tera"] = {
    ["exhaustion"] = 2000,
    ["group"] = {
      [3] = 2000,
    },
    ["id"] = 116,
    ["level"] = 28,
    ["mana"] = 430,
    ["name"] = "Stone Shower Rune",
  },
  ["adori mas vis"] = {
    ["exhaustion"] = 2000,
    ["group"] = {
      [3] = 2000,
    },
    ["id"] = 117,
    ["level"] = 28,
    ["mana"] = 430,
    ["name"] = "Thunderstorm Rune",
  },
  ["adori min vis"] = {
    ["exhaustion"] = 2000,
    ["group"] = {
      [3] = 2000,
    },
    ["id"] = 7,
    ["level"] = 15,
    ["mana"] = 120,
    ["name"] = "Light Magic Missile Rune",
  },
  ["adori san"] = {
    ["exhaustion"] = 2000,
    ["group"] = {
      [3] = 2000,
    },
    ["id"] = 130,
    ["level"] = 27,
    ["mana"] = 300,
    ["name"] = "Holy Missile Rune",
  },
  ["adori tera"] = {
    ["exhaustion"] = 2000,
    ["group"] = {
      [3] = 2000,
    },
    ["id"] = 77,
    ["level"] = 24,
    ["mana"] = 350,
    ["name"] = "Stalagmite Rune",
  },
  ["adori vis"] = {
    ["exhaustion"] = 2000,
    ["group"] = {
      [3] = 2000,
    },
    ["id"] = 8,
    ["level"] = 25,
    ["mana"] = 350,
    ["name"] = "Heavy Magic Missile Rune",
  },
  ["adura gran"] = {
    ["exhaustion"] = 2000,
    ["group"] = {
      [3] = 2000,
    },
    ["id"] = 4,
    ["level"] = 15,
    ["mana"] = 120,
    ["name"] = "Intense Healing Rune",
  },
  ["adura vita"] = {
    ["exhaustion"] = 2000,
    ["group"] = {
      [3] = 2000,
    },
    ["id"] = 5,
    ["level"] = 24,
    ["mana"] = 400,
    ["name"] = "Ultimate Healing Rune",
  },
  ["exana amp res"] = {
    ["exhaustion"] = 16000,
    ["group"] = {
      [3] = 2000,
    },
    ["id"] = 238,
    ["level"] = 250,
    ["mana"] = 80,
    ["name"] = "Divine Dazzle",
  },
  ["exana flam"] = {
    ["exhaustion"] = 6000,
    ["group"] = {
      [2] = 1000,
    },
    ["id"] = 145,
    ["level"] = 30,
    ["mana"] = 30,
    ["name"] = "Cure Burning",
  },
  ["exana ina"] = {
    ["exhaustion"] = 2000,
    ["group"] = {
      [3] = 2000,
    },
    ["id"] = 90,
    ["level"] = 26,
    ["mana"] = 200,
    ["name"] = "Cancel Invisibility",
  },
  ["exana kor"] = {
    ["exhaustion"] = 6000,
    ["group"] = {
      [2] = 1000,
    },
    ["id"] = 144,
    ["level"] = 45,
    ["mana"] = 30,
    ["name"] = "Cure Bleeding",
  },
  ["exana mort"] = {
    ["exhaustion"] = 6000,
    ["group"] = {
      [2] = 1000,
    },
    ["id"] = 147,
    ["level"] = 80,
    ["mana"] = 40,
    ["name"] = "Cure Curse",
  },
  ["exana pox"] = {
    ["exhaustion"] = 6000,
    ["group"] = {
      [2] = 1000,
    },
    ["id"] = 29,
    ["level"] = 10,
    ["mana"] = 30,
    ["name"] = "Cure Poison",
  },
  ["exana vis"] = {
    ["exhaustion"] = 6000,
    ["group"] = {
      [2] = 1000,
    },
    ["id"] = 146,
    ["level"] = 22,
    ["mana"] = 30,
    ["name"] = "Cure Electrification",
  },
  ["exana vita"] = {
    ["exhaustion"] = 2000,
    ["group"] = {
      [3] = 2000,
    },
    ["id"] = 245,
    ["level"] = 14,
    ["mana"] = 50,
    ["name"] = "Cancel Magic Shield",
  },
  ["exani hur"] = {
    ["exhaustion"] = 2000,
    ["group"] = {
      [3] = 2000,
    },
    ["id"] = 81,
    ["level"] = 12,
    ["mana"] = 50,
    ["name"] = "Levitate",
  },
  ["exani tera"] = {
    ["exhaustion"] = 2000,
    ["group"] = {
      [3] = 2000,
    },
    ["id"] = 76,
    ["level"] = 9,
    ["mana"] = 20,
    ["name"] = "Magic Rope",
  },
  ["exeta amp res"] = {
    ["exhaustion"] = 2000,
    ["group"] = {
      [3] = 2000,
    },
    ["id"] = 237,
    ["level"] = 150,
    ["mana"] = 80,
    ["name"] = "Chivalrous Challenge",
  },
  ["exeta con"] = {
    ["exhaustion"] = 2000,
    ["group"] = {
      [3] = 2000,
    },
    ["id"] = 110,
    ["level"] = 45,
    ["mana"] = 350,
    ["name"] = "Enchant Spear",
  },
  ["exeta res"] = {
    ["exhaustion"] = 2000,
    ["group"] = {
      [3] = 2000,
    },
    ["id"] = 93,
    ["level"] = 20,
    ["mana"] = 30,
    ["name"] = "Challenge",
  },
  ["exeta vis"] = {
    ["exhaustion"] = 2000,
    ["group"] = {
      [3] = 2000,
    },
    ["id"] = 92,
    ["level"] = 41,
    ["mana"] = 80,
    ["name"] = "Enchant Staff",
  },
  ["exevo con"] = {
    ["exhaustion"] = 2000,
    ["group"] = {
      [3] = 2000,
    },
    ["id"] = 51,
    ["level"] = 13,
    ["mana"] = 100,
    ["name"] = "Conjure Arrow",
  },
  ["exevo con flam"] = {
    ["exhaustion"] = 2000,
    ["group"] = {
      [3] = 2000,
    },
    ["id"] = 49,
    ["level"] = 25,
    ["mana"] = 290,
    ["name"] = "Conjure Explosive Arrow",
  },
  ["exevo con grav"] = {
    ["exhaustion"] = 2000,
    ["group"] = {
      [3] = 2000,
    },
    ["id"] = 109,
    ["level"] = 33,
    ["mana"] = 180,
    ["name"] = "Conjure Piercing Bolt",
  },
  ["exevo con hur"] = {
    ["exhaustion"] = 2000,
    ["group"] = {
      [3] = 2000,
    },
    ["id"] = 108,
    ["level"] = 24,
    ["mana"] = 160,
    ["name"] = "Conjure Sniper Arrow",
  },
  ["exevo con mort"] = {
    ["exhaustion"] = 2000,
    ["group"] = {
      [3] = 2000,
    },
    ["id"] = 79,
    ["level"] = 17,
    ["mana"] = 140,
    ["name"] = "Conjure Bolt",
  },
  ["exevo con pox"] = {
    ["exhaustion"] = 2000,
    ["group"] = {
      [3] = 2000,
    },
    ["id"] = 48,
    ["level"] = 16,
    ["mana"] = 130,
    ["name"] = "Conjure Poisoned Arrow",
  },
  ["exevo con vis"] = {
    ["exhaustion"] = 2000,
    ["group"] = {
      [3] = 2000,
    },
    ["id"] = 95,
    ["level"] = 59,
    ["mana"] = 700,
    ["name"] = "Conjure Power Bolt",
  },
  ["exevo dis flam hur"] = {
    ["exhaustion"] = 4000,
    ["group"] = {
      2000,
    },
    ["id"] = 167,
    ["level"] = 1,
    ["mana"] = 5,
    ["name"] = "Practise Fire Wave",
  },
  ["exevo flam hur"] = {
    ["exhaustion"] = 4000,
    ["group"] = {
      2000,
    },
    ["id"] = 19,
    ["level"] = 18,
    ["mana"] = 25,
    ["name"] = "Fire Wave",
  },
  ["exevo frigo hur"] = {
    ["exhaustion"] = 4000,
    ["group"] = {
      2000,
    },
    ["id"] = 121,
    ["level"] = 18,
    ["mana"] = 25,
    ["name"] = "Ice Wave",
  },
  ["exevo fur frigo"] = {
    ["exhaustion"] = 6000,
    ["group"] = {
      2000,
    },
    ["id"] = 317,
    ["level"] = 90,
    ["mana"] = 180,
    ["name"] = "Forked Glacier",
  },
  ["exevo fur tera"] = {
    ["exhaustion"] = 6000,
    ["group"] = {
      2000,
    },
    ["id"] = 318,
    ["level"] = 80,
    ["mana"] = 180,
    ["name"] = "Forked Thorns",
  },
  ["exevo gran con grav"] = {
    ["exhaustion"] = 2000,
    ["group"] = {
      [3] = 2000,
    },
    ["id"] = 191,
    ["level"] = 150,
    ["mana"] = 1000,
    ["name"] = "Conjure Royal Star",
  },
  ["exevo gran flam hur"] = {
    ["exhaustion"] = 4000,
    ["group"] = {
      2000,
    },
    ["id"] = 240,
    ["level"] = 38,
    ["mana"] = 120,
    ["name"] = "Great Fire Wave",
  },
  ["exevo gran frigo hur"] = {
    ["exhaustion"] = 8000,
    ["group"] = {
      2000,
    },
    ["id"] = 43,
    ["level"] = 40,
    ["mana"] = 170,
    ["name"] = "Strong Ice Wave",
  },
  ["exevo gran mas flam"] = {
    ["exhaustion"] = 40000,
    ["group"] = {
      4000,
    },
    ["id"] = 24,
    ["level"] = 60,
    ["mana"] = 1100,
    ["name"] = "Hell's Core",
  },
  ["exevo gran mas frigo"] = {
    ["exhaustion"] = 20000,
    ["group"] = {
      4000,
      [7] = 20000,
    },
    ["id"] = 118,
    ["level"] = 60,
    ["mana"] = 1150,
    ["name"] = "Eternal Winter",
  },
  ["exevo gran mas tera"] = {
    ["exhaustion"] = 40000,
    ["group"] = {
      4000,
      [7] = 40000,
    },
    ["id"] = 56,
    ["level"] = 55,
    ["mana"] = 700,
    ["name"] = "Wrath of Nature",
  },
  ["exevo gran mas vis"] = {
    ["exhaustion"] = 40000,
    ["group"] = {
      4000,
    },
    ["id"] = 119,
    ["level"] = 55,
    ["mana"] = 600,
    ["name"] = "Rage of the Skies",
  },
  ["exevo gran mort"] = {
    ["exhaustion"] = 1800000,
    ["group"] = {
      [3] = 2000,
    },
    ["id"] = 92,
    ["level"] = 41,
    ["mana"] = 250,
    ["name"] = "Conjure Wand of Darkness",
  },
  ["exevo gran vis lux"] = {
    ["exhaustion"] = 6000,
    ["group"] = {
      2000,
    },
    ["id"] = 23,
    ["level"] = 29,
    ["mana"] = 110,
    ["name"] = "Great Energy Beam",
  },
  ["exevo infir con"] = {
    ["exhaustion"] = 2000,
    ["group"] = {
      [3] = 2000,
    },
    ["id"] = 176,
    ["level"] = 1,
    ["mana"] = 10,
    ["name"] = "Arrow Call",
  },
  ["exevo infir flam hur"] = {
    ["exhaustion"] = 4000,
    ["group"] = {
      2000,
    },
    ["id"] = 178,
    ["level"] = 1,
    ["mana"] = 8,
    ["name"] = "Scorch",
  },
  ["exevo infir frigo hur"] = {
    ["exhaustion"] = 4000,
    ["group"] = {
      2000,
    },
    ["id"] = 173,
    ["level"] = 1,
    ["mana"] = 8,
    ["name"] = "Chill Out",
  },
  ["exevo mas san"] = {
    ["exhaustion"] = 4000,
    ["group"] = {
      2000,
    },
    ["id"] = 124,
    ["level"] = 50,
    ["mana"] = 160,
    ["name"] = "Divine Caldera",
  },
  ["exevo max mort"] = {
    ["exhaustion"] = 10000,
    ["group"] = {
      2000,
    },
    ["id"] = 260,
    ["level"] = 300,
    ["mana"] = 140,
    ["name"] = "Great Death Beam",
  },
  ["exevo mort ora"] = {
    ["exhaustion"] = 6000,
    ["group"] = {
      2000,
    },
    ["id"] = 310,
    ["level"] = 120,
    ["mana"] = 150,
    ["name"] = "Death Echo",
  },
  ["exevo pan"] = {
    ["exhaustion"] = 2000,
    ["group"] = {
      [3] = 2000,
    },
    ["id"] = 42,
    ["level"] = 14,
    ["mana"] = 120,
    ["name"] = "Food",
  },
  ["exevo tempo mas san"] = {
    ["exhaustion"] = 1000,
    ["group"] = {
      2000,
    },
    ["id"] = 258,
    ["level"] = 300,
    ["mana"] = 160,
    ["name"] = "Divine Grenade",
  },
  ["exevo tera hur"] = {
    ["exhaustion"] = 4000,
    ["group"] = {
      2000,
    },
    ["id"] = 120,
    ["level"] = 38,
    ["mana"] = 170,
    ["name"] = "Terra Wave",
  },
  ["exevo ulus frigo"] = {
    ["exhaustion"] = 22000,
    ["group"] = {
      2000,
      [10] = 22000,
    },
    ["id"] = 262,
    ["level"] = 300,
    ["mana"] = 230,
    ["name"] = "Ice Burst",
  },
  ["exevo ulus tera"] = {
    ["exhaustion"] = 22000,
    ["group"] = {
      2000,
      [10] = 22000,
    },
    ["id"] = 263,
    ["level"] = 300,
    ["mana"] = 230,
    ["name"] = "Terra Burst",
  },
  ["exevo vis hur"] = {
    ["exhaustion"] = 8000,
    ["group"] = {
      2000,
    },
    ["id"] = 13,
    ["level"] = 38,
    ["mana"] = 170,
    ["name"] = "Energy Wave",
  },
  ["exevo vis lux"] = {
    ["exhaustion"] = 4000,
    ["group"] = {
      2000,
    },
    ["id"] = 22,
    ["level"] = 23,
    ["mana"] = 40,
    ["name"] = "Energy Beam",
  },
  ["exiva"] = {
    ["exhaustion"] = 2000,
    ["group"] = {
      [3] = 2000,
    },
    ["id"] = 20,
    ["level"] = 8,
    ["mana"] = 20,
    ["name"] = "Find Person",
  },
  ["exori"] = {
    ["exhaustion"] = 4000,
    ["group"] = {
      2000,
    },
    ["id"] = 80,
    ["level"] = 35,
    ["mana"] = 115,
    ["name"] = "Berserk",
  },
  ["exori amp kor"] = {
    ["exhaustion"] = 18000,
    ["group"] = {
      2000,
    },
    ["id"] = 261,
    ["level"] = 300,
    ["mana"] = 225,
    ["name"] = "Executioner's Throw",
  },
  ["exori amp pug"] = {
    ["exhaustion"] = 14000,
    ["group"] = {
      2000,
    },
    ["id"] = 290,
    ["level"] = 30,
    ["mana"] = 150,
    ["name"] = "Mystic Repulse",
  },
  ["exori amp vis"] = {
    ["exhaustion"] = 8000,
    ["group"] = {
      2000,
    },
    ["id"] = 149,
    ["level"] = 55,
    ["mana"] = 60,
    ["name"] = "Lightning",
  },
  ["exori con"] = {
    ["exhaustion"] = 2000,
    ["group"] = {
      2000,
    },
    ["id"] = 111,
    ["level"] = 23,
    ["mana"] = 25,
    ["name"] = "Ethereal Spear",
  },
  ["exori dir moe"] = {
    ["exhaustion"] = 4000,
    ["group"] = {
      2000,
    },
    ["id"] = 303,
    ["level"] = 60,
    ["mana"] = 135,
    ["name"] = "Ethereal Barrage",
  },
  ["exori dir san"] = {
    ["exhaustion"] = 4000,
    ["group"] = {
      2000,
    },
    ["id"] = 302,
    ["level"] = 70,
    ["mana"] = 175,
    ["name"] = "Divine Barrage",
  },
  ["exori flam"] = {
    ["exhaustion"] = 2000,
    ["group"] = {
      2000,
    },
    ["id"] = 89,
    ["level"] = 14,
    ["mana"] = 20,
    ["name"] = "Flame Strike",
  },
  ["exori frigo"] = {
    ["exhaustion"] = 2000,
    ["group"] = {
      2000,
    },
    ["id"] = 112,
    ["level"] = 15,
    ["mana"] = 20,
    ["name"] = "Ice Strike",
  },
  ["exori gran"] = {
    ["exhaustion"] = 6000,
    ["group"] = {
      2000,
    },
    ["id"] = 105,
    ["level"] = 90,
    ["mana"] = 340,
    ["name"] = "Fierce Berserk",
  },
  ["exori gran con"] = {
    ["exhaustion"] = 8000,
    ["group"] = {
      2000,
    },
    ["id"] = 57,
    ["level"] = 90,
    ["mana"] = 55,
    ["name"] = "Strong Ethereal Spear",
  },
  ["exori gran flam"] = {
    ["exhaustion"] = 8000,
    ["group"] = {
      2000,
    },
    ["id"] = 150,
    ["level"] = 70,
    ["mana"] = 60,
    ["name"] = "Strong Flame Strike",
  },
  ["exori gran frigo"] = {
    ["exhaustion"] = 8000,
    ["group"] = {
      2000,
    },
    ["id"] = 152,
    ["level"] = 80,
    ["mana"] = 60,
    ["name"] = "Strong Ice Strike",
  },
  ["exori gran ico"] = {
    ["exhaustion"] = 30000,
    ["group"] = {
      2000,
    },
    ["id"] = 62,
    ["level"] = 110,
    ["mana"] = 300,
    ["name"] = "Annihilation",
  },
  ["exori gran mas nia"] = {
    ["exhaustion"] = 60000,
    ["group"] = {
      2000,
    },
    ["id"] = 295,
    ["level"] = 300,
    ["mana"] = 425,
    ["name"] = "Spiritual Outburst",
  },
  ["exori gran mas pug"] = {
    ["exhaustion"] = 10000,
    ["group"] = {
      2000,
    },
    ["id"] = 289,
    ["level"] = 90,
    ["mana"] = 300,
    ["name"] = "Greater Flurry of Blows",
  },
  ["exori gran nia"] = {
    ["exhaustion"] = 24000,
    ["group"] = {
      2000,
    },
    ["id"] = 293,
    ["level"] = 125,
    ["mana"] = 210,
    ["name"] = "Devastating Knockout",
  },
  ["exori gran pug"] = {
    ["exhaustion"] = 40000,
    ["group"] = {
      2000,
    },
    ["id"] = 286,
    ["level"] = 110,
    ["mana"] = 325,
    ["name"] = "Forceful Uppercut",
  },
  ["exori gran tera"] = {
    ["exhaustion"] = 8000,
    ["group"] = {
      2000,
    },
    ["id"] = 153,
    ["level"] = 70,
    ["mana"] = 60,
    ["name"] = "Strong Terra Strike",
  },
  ["exori gran vis"] = {
    ["exhaustion"] = 8000,
    ["group"] = {
      2000,
    },
    ["id"] = 151,
    ["level"] = 80,
    ["mana"] = 60,
    ["name"] = "Strong Energy Strike",
  },
  ["exori hur"] = {
    ["exhaustion"] = 6000,
    ["group"] = {
      2000,
    },
    ["id"] = 107,
    ["level"] = 28,
    ["mana"] = 40,
    ["name"] = "Whirlwind Throw",
  },
  ["exori ico"] = {
    ["exhaustion"] = 6000,
    ["group"] = {
      2000,
    },
    ["id"] = 61,
    ["level"] = 16,
    ["mana"] = 30,
    ["name"] = "Brutal Strike",
  },
  ["exori ico scu"] = {
    ["exhaustion"] = 4000,
    ["group"] = {
      2000,
    },
    ["id"] = 315,
    ["level"] = 18,
    ["mana"] = 30,
    ["name"] = "Shield Bash",
  },
  ["exori infir amp pug"] = {
    ["exhaustion"] = 20000,
    ["group"] = {
      2000,
    },
    ["id"] = 300,
    ["level"] = 6,
    ["mana"] = 30,
    ["name"] = "Lesser Mystic Repulse",
  },
  ["exori infir nia"] = {
    ["exhaustion"] = 8000,
    ["group"] = {
      2000,
    },
    ["id"] = 291,
    ["level"] = 1,
    ["mana"] = 18,
    ["name"] = "Tiger Clash",
  },
  ["exori infir pug"] = {
    ["exhaustion"] = 2000,
    ["group"] = {
      2000,
    },
    ["id"] = 284,
    ["level"] = 1,
    ["mana"] = 3,
    ["name"] = "Swift Jab",
  },
  ["exori infir tera"] = {
    ["exhaustion"] = 2000,
    ["group"] = {
      2000,
    },
    ["id"] = 174,
    ["level"] = 1,
    ["mana"] = 6,
    ["name"] = "Mud Attack",
  },
  ["exori infir vis"] = {
    ["exhaustion"] = 2000,
    ["group"] = {
      2000,
    },
    ["id"] = 177,
    ["level"] = 1,
    ["mana"] = 6,
    ["name"] = "Buzz",
  },
  ["exori kor"] = {
    ["exhaustion"] = 12000,
    ["group"] = {
      [3] = 2000,
    },
    ["id"] = 244,
    ["level"] = 275,
    ["mana"] = 300,
    ["name"] = "Sap Strength",
  },
  ["exori kor tempo"] = {
    ["exhaustion"] = 30000,
    ["group"] = {
      [3] = 2000,
      [6] = 30000,
    },
    ["id"] = 312,
    ["level"] = 20,
    ["mana"] = 1500,
    ["name"] = "Aura of Exposed Weakness",
  },
  ["exori mas"] = {
    ["exhaustion"] = 8000,
    ["group"] = {
      2000,
    },
    ["id"] = 106,
    ["level"] = 33,
    ["mana"] = 160,
    ["name"] = "Groundshaker",
  },
  ["exori mas amp pug"] = {
    ["exhaustion"] = 12000,
    ["group"] = {
      2000,
    },
    ["id"] = 301,
    ["level"] = 120,
    ["mana"] = 145,
    ["name"] = "Thousand Fist Blows",
  },
  ["exori mas nia"] = {
    ["exhaustion"] = 8000,
    ["group"] = {
      2000,
    },
    ["id"] = 294,
    ["level"] = 60,
    ["mana"] = 195,
    ["name"] = "Sweeping Takedown",
  },
  ["exori mas pug"] = {
    ["exhaustion"] = 4000,
    ["group"] = {
      2000,
    },
    ["id"] = 287,
    ["level"] = 35,
    ["mana"] = 110,
    ["name"] = "Flurry of Blows",
  },
  ["exori mas res"] = {
    ["exhaustion"] = 10000,
    ["group"] = {
      [3] = 2000,
    },
    ["id"] = 280,
    ["level"] = 175,
    ["mana"] = 80,
    ["name"] = "Balanced Brawl",
  },
  ["exori max flam"] = {
    ["exhaustion"] = 30000,
    ["group"] = {
      2000,
    },
    ["id"] = 154,
    ["level"] = 90,
    ["mana"] = 100,
    ["name"] = "Ultimate Flame Strike",
  },
  ["exori max frigo"] = {
    ["exhaustion"] = 30000,
    ["group"] = {
      2000,
    },
    ["id"] = 156,
    ["level"] = 100,
    ["mana"] = 100,
    ["name"] = "Ultimate Ice Strike",
  },
  ["exori max tera"] = {
    ["exhaustion"] = 30000,
    ["group"] = {
      2000,
    },
    ["id"] = 157,
    ["level"] = 90,
    ["mana"] = 100,
    ["name"] = "Ultimate Terra Strike",
  },
  ["exori max vis"] = {
    ["exhaustion"] = 30000,
    ["group"] = {
      2000,
    },
    ["id"] = 155,
    ["level"] = 100,
    ["mana"] = 100,
    ["name"] = "Ultimate Energy Strike",
  },
  ["exori med pug"] = {
    ["exhaustion"] = 4000,
    ["group"] = {
      2000,
    },
    ["id"] = 288,
    ["level"] = 70,
    ["mana"] = 180,
    ["name"] = "Chained Penance",
  },
  ["exori min"] = {
    ["exhaustion"] = 6000,
    ["group"] = {
      2000,
    },
    ["id"] = 59,
    ["level"] = 70,
    ["mana"] = 200,
    ["name"] = "Front Sweep",
  },
  ["exori min flam"] = {
    ["exhaustion"] = 2000,
    ["group"] = {
      2000,
    },
    ["id"] = 169,
    ["level"] = 8,
    ["mana"] = 6,
    ["name"] = "Apprentice's Strike",
  },
  ["exori moe"] = {
    ["exhaustion"] = 12000,
    ["group"] = {
      [3] = 2000,
    },
    ["id"] = 243,
    ["level"] = 275,
    ["mana"] = 400,
    ["name"] = "Expose Weakness",
  },
  ["exori moe ico"] = {
    ["exhaustion"] = 2000,
    ["group"] = {
      2000,
    },
    ["id"] = 148,
    ["level"] = 16,
    ["mana"] = 20,
    ["name"] = "Physical Strike",
  },
  ["exori moe tempo"] = {
    ["exhaustion"] = 30000,
    ["group"] = {
      [3] = 2000,
      [6] = 30000,
    },
    ["id"] = 311,
    ["level"] = 20,
    ["mana"] = 1500,
    ["name"] = "Aura of Sapped Strength",
  },
  ["exori mort"] = {
    ["exhaustion"] = 2000,
    ["group"] = {
      2000,
    },
    ["id"] = 87,
    ["level"] = 16,
    ["mana"] = 20,
    ["name"] = "Death Strike",
  },
  ["exori nia"] = {
    ["exhaustion"] = 8000,
    ["group"] = {
      2000,
    },
    ["id"] = 292,
    ["level"] = 18,
    ["mana"] = 50,
    ["name"] = "Greater Tiger Clash",
  },
  ["exori pug"] = {
    ["exhaustion"] = 4000,
    ["group"] = {
      2000,
    },
    ["id"] = 285,
    ["level"] = 14,
    ["mana"] = 30,
    ["name"] = "Double Jab",
  },
  ["exori san"] = {
    ["exhaustion"] = 2000,
    ["group"] = {
      2000,
    },
    ["id"] = 122,
    ["level"] = 40,
    ["mana"] = 20,
    ["name"] = "Divine Missile",
  },
  ["exori scu"] = {
    ["exhaustion"] = 6000,
    ["group"] = {
      2000,
    },
    ["id"] = 316,
    ["level"] = 30,
    ["mana"] = 90,
    ["name"] = "Shield Slam",
  },
  ["exori tera"] = {
    ["exhaustion"] = 2000,
    ["group"] = {
      2000,
    },
    ["id"] = 113,
    ["level"] = 13,
    ["mana"] = 20,
    ["name"] = "Terra Strike",
  },
  ["exori vis"] = {
    ["exhaustion"] = 2000,
    ["group"] = {
      2000,
    },
    ["id"] = 88,
    ["level"] = 12,
    ["mana"] = 20,
    ["name"] = "Energy Strike",
  },
  ["exura"] = {
    ["exhaustion"] = 1000,
    ["group"] = {
      [2] = 1000,
    },
    ["id"] = 1,
    ["level"] = 8,
    ["mana"] = 20,
    ["name"] = "Light Healing",
  },
  ["exura dis"] = {
    ["exhaustion"] = 1000,
    ["group"] = {
      [2] = 1000,
    },
    ["id"] = 166,
    ["level"] = 1,
    ["mana"] = 5,
    ["name"] = "Practice Healing",
  },
  ["exura gran"] = {
    ["exhaustion"] = 1000,
    ["group"] = {
      [2] = 1000,
    },
    ["id"] = 2,
    ["level"] = 20,
    ["mana"] = 70,
    ["name"] = "Intense Healing",
  },
  ["exura gran ico"] = {
    ["exhaustion"] = 600000,
    ["group"] = {
      [2] = 1000,
    },
    ["id"] = 158,
    ["level"] = 80,
    ["mana"] = 200,
    ["name"] = "Intense Wound Cleansing",
  },
  ["exura gran mas res"] = {
    ["exhaustion"] = 2000,
    ["group"] = {
      [2] = 1000,
    },
    ["id"] = 82,
    ["level"] = 36,
    ["mana"] = 150,
    ["name"] = "Mass Healing",
  },
  ["exura gran san"] = {
    ["exhaustion"] = 1000,
    ["group"] = {
      [2] = 1000,
    },
    ["id"] = 36,
    ["level"] = 60,
    ["mana"] = 210,
    ["name"] = "Salvation",
  },
  ["exura gran sio"] = {
    ["exhaustion"] = 60000,
    ["group"] = {
      [2] = 1000,
    },
    ["id"] = 242,
    ["level"] = 300,
    ["mana"] = 400,
    ["name"] = "Nature's Embrace",
  },
  ["exura gran tio"] = {
    ["exhaustion"] = 1000,
    ["group"] = {
      [2] = 1000,
    },
    ["id"] = 273,
    ["level"] = 80,
    ["mana"] = 210,
    ["name"] = "Spirit Mend",
  },
  ["exura ico"] = {
    ["exhaustion"] = 1000,
    ["group"] = {
      [2] = 1000,
    },
    ["id"] = 123,
    ["level"] = 8,
    ["mana"] = 40,
    ["name"] = "Wound Cleansing",
  },
  ["exura infir"] = {
    ["exhaustion"] = 1000,
    ["group"] = {
      [2] = 1000,
    },
    ["id"] = 174,
    ["level"] = 1,
    ["mana"] = 6,
    ["name"] = "Magic Patch",
  },
  ["exura infir ico"] = {
    ["exhaustion"] = 1000,
    ["group"] = {
      [2] = 1000,
    },
    ["id"] = 170,
    ["level"] = 1,
    ["mana"] = 10,
    ["name"] = "Bruise Bane",
  },
  ["exura mas nia"] = {
    ["exhaustion"] = 8000,
    ["group"] = {
      [2] = 2000,
    },
    ["id"] = 296,
    ["level"] = 150,
    ["mana"] = 250,
    ["name"] = "Mass Spirit Mend",
  },
  ["exura max vita"] = {
    ["exhaustion"] = 6000,
    ["group"] = {
      [2] = 1000,
    },
    ["id"] = 241,
    ["level"] = 300,
    ["mana"] = 260,
    ["name"] = "Restoration",
  },
  ["exura med ico"] = {
    ["exhaustion"] = 1000,
    ["group"] = {
      [2] = 1000,
    },
    ["id"] = 239,
    ["level"] = 300,
    ["mana"] = 90,
    ["name"] = "Fair Wound Cleansing",
  },
  ["exura san"] = {
    ["exhaustion"] = 1000,
    ["group"] = {
      [2] = 1000,
    },
    ["id"] = 125,
    ["level"] = 35,
    ["mana"] = 160,
    ["name"] = "Divine Healing",
  },
  ["exura sio"] = {
    ["exhaustion"] = 1000,
    ["group"] = {
      [2] = 1000,
    },
    ["id"] = 84,
    ["level"] = 18,
    ["mana"] = 120,
    ["name"] = "Heal Friend",
  },
  ["exura tio sio"] = {
    ["exhaustion"] = 2000,
    ["group"] = {
      [2] = 1000,
    },
    ["id"] = 297,
    ["level"] = 18,
    ["mana"] = 120,
    ["name"] = "Restore Balance",
  },
  ["exura vita"] = {
    ["exhaustion"] = 1000,
    ["group"] = {
      [2] = 1000,
    },
    ["id"] = 3,
    ["level"] = 30,
    ["mana"] = 160,
    ["name"] = "Ultimate Healing",
  },
  ["utamo mas sio"] = {
    ["exhaustion"] = 2000,
    ["group"] = {
      [3] = 2000,
    },
    ["id"] = 127,
    ["level"] = 32,
    ["mana"] = 90,
    ["name"] = "Protect Party",
  },
  ["utamo tempo"] = {
    ["exhaustion"] = 2000,
    ["group"] = {
      [3] = 2000,
      [11] = 30000,
    },
    ["id"] = 132,
    ["level"] = 55,
    ["mana"] = 200,
    ["name"] = "Protector",
  },
  ["utamo tempo san"] = {
    ["exhaustion"] = 10000,
    ["group"] = {
      [3] = 2000,
    },
    ["id"] = 134,
    ["level"] = 55,
    ["mana"] = 400,
    ["name"] = "Swift Foot",
  },
  ["utamo tio"] = {
    ["exhaustion"] = 600000,
    ["group"] = {
      [3] = 2000,
    },
    ["id"] = 281,
    ["level"] = 150,
    ["mana"] = 500,
    ["name"] = "Focus Serenity",
  },
  ["utamo vita"] = {
    ["exhaustion"] = 14000,
    ["group"] = {
      [3] = 2000,
    },
    ["id"] = 44,
    ["level"] = 14,
    ["mana"] = 50,
    ["name"] = "Magic Shield",
  },
  ["utana vid"] = {
    ["exhaustion"] = 2000,
    ["group"] = {
      [3] = 2000,
    },
    ["id"] = 45,
    ["level"] = 35,
    ["mana"] = 440,
    ["name"] = "Invisibility",
  },
  ["utani gran hur"] = {
    ["exhaustion"] = 2000,
    ["group"] = {
      [3] = 2000,
    },
    ["id"] = 39,
    ["level"] = 20,
    ["mana"] = 100,
    ["name"] = "Strong Haste",
  },
  ["utani hur"] = {
    ["exhaustion"] = 2000,
    ["group"] = {
      [3] = 2000,
    },
    ["id"] = 6,
    ["level"] = 14,
    ["mana"] = 60,
    ["name"] = "Haste",
  },
  ["utani tempo hur"] = {
    ["exhaustion"] = 2000,
    ["group"] = {
      [3] = 2000,
    },
    ["id"] = 131,
    ["level"] = 25,
    ["mana"] = 100,
    ["name"] = "Charge",
  },
  ["uteta flam"] = {
    ["exhaustion"] = 30000,
    ["group"] = {
      [3] = 2000,
      [11] = 30000,
    },
    ["id"] = 304,
    ["level"] = 20,
    ["mana"] = 400,
    ["name"] = "Master of Flames",
  },
  ["uteta mort"] = {
    ["exhaustion"] = 30000,
    ["group"] = {
      [3] = 2000,
      [11] = 30000,
    },
    ["id"] = 306,
    ["level"] = 20,
    ["mana"] = 400,
    ["name"] = "Master of Decay",
  },
  ["uteta res dru"] = {
    ["exhaustion"] = 7200000,
    ["group"] = {
      [3] = 2000,
    },
    ["id"] = 267,
    ["level"] = 300,
    ["mana"] = 2200,
    ["name"] = "Avatar of Nature",
  },
  ["uteta res eq"] = {
    ["exhaustion"] = 7200000,
    ["group"] = {
      [3] = 2000,
    },
    ["id"] = 264,
    ["level"] = 300,
    ["mana"] = 800,
    ["name"] = "Avatar of Steel",
  },
  ["uteta res sac"] = {
    ["exhaustion"] = 7200000,
    ["group"] = {
      [3] = 2000,
    },
    ["id"] = 265,
    ["level"] = 300,
    ["mana"] = 1500,
    ["name"] = "Avatar of Light",
  },
  ["uteta res tio"] = {
    ["exhaustion"] = 7200000,
    ["group"] = {
      [3] = 2000,
    },
    ["id"] = 283,
    ["level"] = 300,
    ["mana"] = 1200,
    ["name"] = "Avatar of Balance",
  },
  ["uteta res ven"] = {
    ["exhaustion"] = 7200000,
    ["group"] = {
      [3] = 2000,
    },
    ["id"] = 266,
    ["level"] = 300,
    ["mana"] = 2200,
    ["name"] = "Avatar of Storm",
  },
  ["uteta tio"] = {
    ["exhaustion"] = 2000,
    ["group"] = {
      [3] = 2000,
    },
    ["id"] = 277,
    ["level"] = 150,
    ["mana"] = 110,
    ["name"] = "Mentor Other",
  },
  ["uteta vis"] = {
    ["exhaustion"] = 30000,
    ["group"] = {
      [3] = 2000,
      [11] = 30000,
    },
    ["id"] = 305,
    ["level"] = 20,
    ["mana"] = 400,
    ["name"] = "Master of Thunder",
  },
  ["utevo gran lux"] = {
    ["exhaustion"] = 2000,
    ["group"] = {
      [3] = 2000,
    },
    ["id"] = 11,
    ["level"] = 13,
    ["mana"] = 60,
    ["name"] = "Great Light",
  },
  ["utevo gran res dru"] = {
    ["exhaustion"] = 0,
    ["group"] = {
      [3] = 2000,
    },
    ["id"] = 197,
    ["level"] = 200,
    ["mana"] = 3000,
    ["name"] = "Druid familiar",
  },
  ["utevo gran res eq"] = {
    ["exhaustion"] = 0,
    ["group"] = {
      [3] = 2000,
    },
    ["id"] = 194,
    ["level"] = 200,
    ["mana"] = 1000,
    ["name"] = "Knight familiar",
  },
  ["utevo gran res sac"] = {
    ["exhaustion"] = 0,
    ["group"] = {
      [3] = 2000,
    },
    ["id"] = 195,
    ["level"] = 200,
    ["mana"] = 2000,
    ["name"] = "Paladin familiar",
  },
  ["utevo gran res tio"] = {
    ["exhaustion"] = 0,
    ["group"] = {
      [3] = 2000,
    },
    ["id"] = 282,
    ["level"] = 200,
    ["mana"] = 1500,
    ["name"] = "Summon Monk Familiar",
  },
  ["utevo gran res ven"] = {
    ["exhaustion"] = 0,
    ["group"] = {
      [3] = 2000,
    },
    ["id"] = 196,
    ["level"] = 200,
    ["mana"] = 3000,
    ["name"] = "Sorcerer familiar",
  },
  ["utevo grav san"] = {
    ["exhaustion"] = 32000,
    ["group"] = {
      [3] = 2000,
    },
    ["id"] = 268,
    ["level"] = 300,
    ["mana"] = 500,
    ["name"] = "Divine Empowerment",
  },
  ["utevo lux"] = {
    ["exhaustion"] = 2000,
    ["group"] = {
      [3] = 2000,
    },
    ["id"] = 10,
    ["level"] = 8,
    ["mana"] = 20,
    ["name"] = "Light",
  },
  ["utevo mas sio"] = {
    ["exhaustion"] = 300000,
    ["group"] = {
      [3] = 1000,
    },
    ["id"] = 278,
    ["level"] = 32,
    ["mana"] = 75,
    ["name"] = "Enlighten Party",
  },
  ["utevo nia"] = {
    ["exhaustion"] = 120000,
    ["group"] = {
      [3] = 2000,
    },
    ["id"] = 279,
    ["level"] = 275,
    ["mana"] = 500,
    ["name"] = "Focus Harmony",
  },
  ["utevo res"] = {
    ["exhaustion"] = 2000,
    ["group"] = {
      [3] = 2000,
    },
    ["id"] = 9,
    ["level"] = 25,
    ["mana"] = 0,
    ["name"] = "Summon Creature",
  },
  ["utevo res ina"] = {
    ["exhaustion"] = 2000,
    ["group"] = {
      [3] = 2000,
    },
    ["id"] = 38,
    ["level"] = 23,
    ["mana"] = 100,
    ["name"] = "Creature Illusion",
  },
  ["utevo vis lux"] = {
    ["exhaustion"] = 2000,
    ["group"] = {
      [3] = 2000,
    },
    ["id"] = 75,
    ["level"] = 26,
    ["mana"] = 140,
    ["name"] = "Ultimate Light",
  },
  ["utito dru"] = {
    ["exhaustion"] = 10000,
    ["group"] = {
      [3] = 2000,
      [11] = 10000,
    },
    ["id"] = 319,
    ["level"] = 20,
    ["mana"] = 400,
    ["name"] = "Elemental Synthesis",
  },
  ["utito mas sio"] = {
    ["exhaustion"] = 2000,
    ["group"] = {
      [3] = 2000,
    },
    ["id"] = 126,
    ["level"] = 32,
    ["mana"] = 60,
    ["name"] = "Train Party",
  },
  ["utito tempo"] = {
    ["exhaustion"] = 2000,
    ["group"] = {
      [3] = 2000,
      [11] = 30000,
    },
    ["id"] = 133,
    ["level"] = 60,
    ["mana"] = 290,
    ["name"] = "Blood Rage",
  },
  ["utito tempo san"] = {
    ["exhaustion"] = 10000,
    ["group"] = {
      [3] = 2000,
    },
    ["id"] = 135,
    ["level"] = 60,
    ["mana"] = 450,
    ["name"] = "Sharpshooter",
  },
  ["utito virtu"] = {
    ["exhaustion"] = 10000,
    ["group"] = {
      [3] = 2000,
      [11] = 30000,
    },
    ["id"] = 275,
    ["level"] = 20,
    ["mana"] = 210,
    ["name"] = "Virtue of Justice",
  },
  ["utori con"] = {
    ["exhaustion"] = 2000,
    ["group"] = {
      [3] = 2000,
      [11] = 10000,
    },
    ["id"] = 313,
    ["level"] = 20,
    ["mana"] = 250,
    ["name"] = "Sharpshooter (Stance)",
  },
  ["utori flam"] = {
    ["exhaustion"] = 30000,
    ["group"] = {
      2000,
    },
    ["id"] = 138,
    ["level"] = 26,
    ["mana"] = 30,
    ["name"] = "Ignite",
  },
  ["utori hur"] = {
    ["exhaustion"] = 2000,
    ["group"] = {
      [3] = 2000,
      [11] = 10000,
    },
    ["id"] = 314,
    ["level"] = 20,
    ["mana"] = 250,
    ["name"] = "Divine Defiance",
  },
  ["utori kor"] = {
    ["exhaustion"] = 30000,
    ["group"] = {
      2000,
    },
    ["id"] = 141,
    ["level"] = 40,
    ["mana"] = 30,
    ["name"] = "Inflict Wound",
  },
  ["utori mas sio"] = {
    ["exhaustion"] = 2000,
    ["group"] = {
      [3] = 2000,
    },
    ["id"] = 129,
    ["level"] = 32,
    ["mana"] = 120,
    ["name"] = "Enchant Party",
  },
  ["utori mort"] = {
    ["exhaustion"] = 40000,
    ["group"] = {
      2000,
    },
    ["id"] = 139,
    ["level"] = 75,
    ["mana"] = 30,
    ["name"] = "Curse",
  },
  ["utori pox"] = {
    ["exhaustion"] = 40000,
    ["group"] = {
      2000,
    },
    ["id"] = 142,
    ["level"] = 50,
    ["mana"] = 30,
    ["name"] = "Envenom",
  },
  ["utori san"] = {
    ["exhaustion"] = 40000,
    ["group"] = {
      2000,
    },
    ["id"] = 143,
    ["level"] = 70,
    ["mana"] = 30,
    ["name"] = "Holy Flash",
  },
  ["utori virtu"] = {
    ["exhaustion"] = 2000,
    ["group"] = {
      [3] = 2000,
      [11] = 30000,
    },
    ["id"] = 274,
    ["level"] = 20,
    ["mana"] = 210,
    ["name"] = "Virtue of Harmony",
  },
  ["utori vis"] = {
    ["exhaustion"] = 30000,
    ["group"] = {
      2000,
    },
    ["id"] = 140,
    ["level"] = 34,
    ["mana"] = 30,
    ["name"] = "Electrify",
  },
  ["utura"] = {
    ["exhaustion"] = 60000,
    ["group"] = {
      [2] = 1000,
    },
    ["id"] = 159,
    ["level"] = 50,
    ["mana"] = 75,
    ["name"] = "Recovery",
  },
  ["utura gran"] = {
    ["exhaustion"] = 1000,
    ["group"] = {
      [2] = 1000,
    },
    ["id"] = 160,
    ["level"] = 100,
    ["mana"] = 165,
    ["name"] = "Intense Recovery",
  },
  ["utura mas sio"] = {
    ["exhaustion"] = 2000,
    ["group"] = {
      [3] = 2000,
    },
    ["id"] = 128,
    ["level"] = 32,
    ["mana"] = 120,
    ["name"] = "Heal Party",
  },
  ["utura sio"] = {
    ["exhaustion"] = 10000,
    ["group"] = {
      [3] = 2000,
      [11] = 10000,
    },
    ["id"] = 309,
    ["level"] = 20,
    ["mana"] = 400,
    ["name"] = "Shared Conservation",
  },
  ["utura tio"] = {
    ["exhaustion"] = 2000,
    ["group"] = {
      [3] = 2000,
      [11] = 30000,
    },
    ["id"] = 276,
    ["level"] = 20,
    ["mana"] = 210,
    ["name"] = "Virtue of Sustain",
  },
}
